---
- name: Установка Prometheus и PostgreSQL на Debian 11
  hosts: your_server
  become: true

  tasks:
    - name: Установка Python для Ansible
      raw: apt-get update && apt-get install -y python3

    - name: Установка ролей Ansible для Prometheus и PostgreSQL
      ansible-galaxy:
        name: community.general
        state: present

    - name: Установка PostgreSQL
      community.general.postgresql_server:
        version: 13
        encoding: UTF8
        locale: en_US.utf8
        lc_collate: en_US.utf8
        lc_ctype: en_US.utf8
        walmgr: false
        autovacuum: true

    - name: Установка Prometheus
      community.general.prometheus:
        version: 2.30.1
        global_config:
          scrape_interval: 15s
          evaluation_interval: 15s
        scrape_configs:
          - job_name: 'node'
            static_configs:
              - targets: ['localhost:9100']  # Замените localhost:9100 на адреса ваших узлов

