---
- name: Install Prometheus and PostgreSQL on Debian 11
  hosts: servers
  become: true  # Позволяет выполнять команды с привилегиями суперпользователя
  #become_method: sudo #я под рутом буду делать(вообще конечно надо под ТУЗ, но написано же "простой скрипт")

  tasks:
    - name: Install PostgreSQL
      apt:  # Модуль apt используется для управления пакетами Debian
        name: postgresql  # Устанавливаем пакет PostgreSQL
        state: present  # Убедимся, что пакет установлен

    - name: Install Prometheus
      apt:  # Используем модуль apt для установки пакетов Debian
        name: prometheus  # Устанавливаем пакет Prometheus
        state: present  # Убедимся, что пакет установлен

    - name: Start and activate PostgreSQL
      service:  # Модуль service используется для управления службами
        name: postgresql  # Указываем имя службы PostgreSQL
        state: started  # Запускаем службу
        enabled: yes  # Активируем автозагрузку службы при старте системы

    - name: Start and activate Prometheus
      service:  # Модуль service используется для управления службами
        name: prometheus  # Указываем имя службы Prometheus
        state: started  # Запускаем службу
        enabled: yes  # Активируем автозагрузку службы при старте системы

